# Site settings
title: Kaung Htet Myat
description: 
baseurl: ""

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Navigation
header_pages:
  - firesides.md

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
