# Site settings
title: Kaung Htet Myat
description: 
baseurl: ""

# Build settings
markdown: kramdown
remote_theme: pages-themes/primer@v0.2.0
plugins:
- jekyll-remote-theme

# Navigation
header_pages:
  - firesides.md

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
