# Site settings
theme: jekyll-theme-minimal
title: Kaung Htet Myat
description: AI Engineer
baseurl: ""
url: "https://kaung-htet-myat.github.io"
github_username: kaung-htet-myat

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Navigation
header_pages:
  - index.md
  - blogs.md
  - papers.md

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
