# Site settings
title: 
description: 
baseurl: ""
url: "https://kaung-htet-myat.github.io"
github_username: kaung-htet-myat

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Navigation
header_pages:
  - firesides.md

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
