# Site settings
title: Kaung Htet Myat
description: AI Engineer
baseurl: ""
url: "https://kaung-htet-myat.github.io"
github_username: kaung-htet-myat

# Build settings
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

# Navigation
header_pages:
  - index.md
  - firesides.md

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
